Create interface frame
thanhnx-vbee/vbee-pes-league pull request #1
Opened 2023-05-08 03:25 UTC by ThuKuRu

2023-05-08 03:58 UTC, thanhnx-vbee requested changes

2023-05-08 03:58 UTC, thanhnx-vbee commented on src/containers/Layout/index.jsx
> +  const useStyles = makeStyles((theme) => ({
Chuyển phần style ra ngoài 1 file khác, tên file:` index.style.js`

2023-05-08 04:06 UTC, thanhnx-vbee requested changes

2023-05-08 04:06 UTC, thanhnx-vbee commented on src/containers/Layout/match.jsx
> +const match = () => {
Viết hoa tên component và tên file jsx, tương tự với các file jsx và các component khác

2023-05-08 04:06 UTC, thanhnx-vbee commented on src/containers/Home/index.jsx
> +// eslint-disable-next-line import/no-named-as-default, import/no-named-as-default-member
xóa đi

2023-05-08 04:06 UTC, thanhnx-vbee commented on src/containers/Layout/home.jsx
> +  const useStyles = makeStyles((theme) => ({
Chuyển style ra ngoài

2023-05-11 02:41 UTC, loipnb-vbee requested changes

2023-05-11 02:41 UTC, loipnb-vbee commented on src/containers/Layout/index.jsx
> +  const [value, setValue] = React.useState('en');
Dùng state dạng [nameValue,setNameValue]=useState(value)
không dùng React.useState('');

2023-05-11 02:41 UTC, loipnb-vbee commented on src/apis/matchAPI.js
> +  console.log(data);
xóa console.log()

2023-05-11 02:41 UTC, loipnb-vbee commented on src/containers/Component/Component.jsx
> +    const fetchData = async () => {
để hàm fectchData ra ngoài useEffect()

2023-05-11 02:41 UTC, loipnb-vbee commented on src/apis/matchAPI.js
> +  const response = await fetch(
Nên dùng axios()

2023-05-11 02:41 UTC, loipnb-vbee commented on src/containers/Match/HomePage/index.style.js
> +
Không nên khai báo nhiều lần styled.div. Khai báo 1 lần tên styled chung trong đó chứa các tên styled con của nó.Triển khai các tên styled con trong styled.div' ..... ' giống khai báo bên CSS

2023-05-22 04:44 UTC, thanhnx-vbee requested changes

2023-05-22 04:44 UTC, thanhnx-vbee commented on src/containers/Component/Component.jsx
Đây là Compoent gì ??
Đăt tên file trùng với tên component và mang ý nghĩa chức năng của component chứ không đặt tên chung chung.

2023-05-22 04:44 UTC, thanhnx-vbee commented on src/containers/Component/MatchCalendar/MatchCalendar.jsx
> +          <div className="subCalendarList">
- Viết thành 1 component thể hiện lịch thi đấu
- Viết 1 file json or js là dữ liệu lịch thi đấu sau đó sử dụng map để render chứ không viết thủ công hết ra như nà

2023-05-22 23:27 UTC, loipnb-vbee commented on src/containers/Match/HomePage/index.style.js
> +export {};
delete export null

2023-05-29 07:05 UTC, loipnb-vbee approved these changes

2023-05-29 07:17 UTC, thanhnx-vbee approved these changes

2023-05-29 07:17 UTC, merged